scope: "ft.onto.base_ontology.Sentence"
feature_scheme:
  text_tag:
    type: "data_input"
    extractor:
      class_name: "forte.data.extractors.AttributeExtractor"
      config:
        entry_type: "ft.onto.base_ontology.Token"
        vocab_method: "indexing"
        attribute: "text"
  char_tag:
    type: "data_input"
    extractor:
      class_name: "forte.data.extractors.CharExtractor"
      config:
        entry_type: "ft.onto.base_ontology.Token"
        vocab_method: "indexing"
  raw_text_tag:
    type: "data_input"
      extractor:
        class_name: "forte.data.extractors.AttributeExtractor"
        config:
          entry_type: "ft.onto.base_ontology.Token"
          vocab_method: "raw"
          attribute: "text"
          need_pad: False
    converter:
      to_numpy: False
      to_torch: False
  pred_link_tag:
    type: "data_output"
    extractor:
      class_name: "forte.data.extractors.LinkExtractor"
      config:
        entry_type: "ft.onto.base_ontology.PredicateLink"
        attribute: "arg_type"
        tagging_unit: "ft.onto.base_ontology.Token"
        vocab_method: "indexing"
        need_pad: False
    converter:
      to_numpy: False
      to_torch: False
