train_path: "classification_data/train/"
val_path: "classification_data/dev/"
test_path: "classification_data/test/"
train_state_path: "train_state.pkl"

num_epochs: 3
batch_size_tokens: 2
test_batch_size: 2

max_char_length: 45
num_char_pad: 2
