# This provides a configuration for inference only

- type: "forte.data.readers.MultiPackSentenceReader"
  configs:
    input_pack_name: "input_src"
    output_pack_name: "output_tgt"

- type: "forte.processors.third_party.TextGenerationProcessor"
  configs:
    max_decoding_length: 128
    temperature: 0.7
    top_k: 40
    pretrained_model_name: "gpt2-small"
    input_pack_name: "input_src"
    output_pack_name: "output_tgt"
    batcher:
      batch_size: 64

- type: "forte.processors.third_party.NLTKWordTokenizer"
  configs:
    selector:
      type: "forte.data.selector.NameMatchSelector"
      kwargs:
        select_name: "output_tgt"

- type: "forte.processors.third_party.NLTKPOSTagger"
  configs:
    selector:
      type: "forte.data.selector.NameMatchSelector"
      kwargs:
        select_name: "output_tgt"

