# This provides a configuration for inference only

Reader:
  type: "forte.data.readers.PlainSentenceTxtgenReader"
  kwargs: null

Processors:
  - type: "forte.processors.TxtgenPredictor"
    kwargs:
    hparams:
      config_path:
      overwrite_configs:
        max_decoding_length: 128
        temperature: 0.7
        top_k: 40
        pretrained_model_name: "117M"
        input_pack_name: "input_src"
        output_pack_name: "output_tgt"
        batch_size: 10
  - type: "forte.processors.nltk_processors.NLTKWordTokenizer"
    hparams:
      overwrite_configs:
        selector:
          type: "forte.data.selector.NameMatchSelector"
          kwargs:
            select_name: output_tgt
  - type: "forte.processors.nltk_processors.NLTKPOSTagger"
    hparams:
      overwrite_configs:
        selector:
          type: "forte.data.selector.NameMatchSelector"
          kwargs:
            select_name: output_tgt
