output_hidden_size: 128
dropout_rate: 0.3

word_emb:
    dim: 100

char_emb:
    dim: 30
    initializer:
        'type': 'normal_'

char_cnn_conv:
    in_channels: 30
    out_channels: 30
    kernel_size: 3
    padding: 2

bilstm_sentence_encoder:
    rnn_cell_fw:
        # Input size should be the sum of char_embed.dim and word_emb.dim
        input_size: 130
        type: LSTMCell
        kwargs:
            num_units: 128
    rnn_cell_share_config: yes
    output_layer_fw:
        num_layers: 0
    output_layer_share_config: yes

learning_rate: 0.01
momentum: 0.9
decay_interval: 1
decay_rate: 0.05

random_seed: 1234

initializer:
    "type": "xavier_uniform_"

# path to save model
model_path: "best_ner_crf_model.ckpt"

# path to save resources
resource_dir: "resources/"
