data:
  relative_path: "data/collectionandqueries"

reader:
  pack_name: "query"

query_creator:
  size: 5
  field: "content"
  query_pack_name: "query"

create_index:
  batch_size: 10000
  fields:
    - doc_id
    - content
  indexer:
    name: "ElasticSearchIndexer"
    hparams:
      index_name: "elastic_indexer"
      hosts: "localhost:9200"
      algorithm: "bm25"
    other_kwargs:
      request_timeout: 60
      refresh: true

indexer:
  query_pack_name: "query"
  index_config:
    index_name: "elastic_indexer"
    hosts: "localhost:9200"
    algorithm: "bm25"
  field: "content"
  response_pack_name_prefix: "passage"

writer:
  output_file: "output/results_eval.tsv"

evaluator:
  pack_name: "query"
  ground_truth_file: "data/collectionandqueries/query_doc_id.tsv"
  input_file: "data/collectionandqueries/qrels.dev.small.tsv"
  output_file: "output/results_dev.tsv"

reranker:
  size: 5
  pretrained_model_name: "bert-base-uncased"
  model_dir: "models"
  query_pack_name: "query"
  field: "content"
  max_seq_length: 512
